@echo off
chcp 65001 >nul 2>&1
title Kuroneko Push Handover Script
echo ============================================================
echo  Kuroneko - Push Handover Script
echo  Generated by M3 milestone automation
echo ============================================================
echo.

REM ── Step 1: Verify current branch ──────────────────────────
echo [1/6] Checking current branch...
for /f "tokens=*" %%b in ('git rev-parse --abbrev-ref HEAD') do set CURR_BRANCH=%%b
if NOT "%CURR_BRANCH%"=="main" (
    echo [ABORT] You are on branch: %CURR_BRANCH%
    echo         This script only pushes from 'main'.
    echo         Run: git checkout main
    pause
    exit /b 1
)
echo [OK] On branch: main

REM ── Step 2: Show ahead count ────────────────────────────────
echo.
echo [2/6] Checking commits ahead of origin/main...
for /f "tokens=*" %%n in ('git rev-list --count origin/main..HEAD') do set AHEAD=%%n
echo       Local main is ahead of origin/main by %AHEAD% commit(s).

REM ── Step 3: Show commits to be pushed ───────────────────────
echo.
echo [3/6] Commits to be pushed:
echo ------------------------------------------------------------
git --no-pager log --oneline origin/main..HEAD
echo ------------------------------------------------------------

REM ── Step 4: Confirm ─────────────────────────────────────────
echo.
echo [4/6] About to push %AHEAD% commit(s) to origin/main
echo       Remote: https://github.com/shinjiyu/utlraKuroneko.git
echo.
set /p CONFIRM="Type YES to proceed with push: "
if NOT "%CONFIRM%"=="YES" (
    echo [ABORT] Push cancelled by user.
    pause
    exit /b 1
)

REM ── Step 5: Pull first (safety) ─────────────────────────────
echo.
echo [5/6] Pulling latest from origin/main to avoid conflicts...
git pull --rebase origin main
if ERRORLEVEL 1 (
    echo [WARN] git pull had issues. You may need to resolve conflicts.
    echo        After resolving, re-run this script or push manually.
    pause
    exit /b 1
)
echo [OK] Pull succeeded.

REM ── Step 6: Push ────────────────────────────────────────────
echo.
echo [6/6] Pushing to origin/main...
git push origin main
if ERRORLEVEL 1 (
    echo [ERROR] git push failed. Check network / credentials.
    pause
    exit /b 1
)
echo.
echo ============================================================
echo  Push completed successfully!
echo ============================================================
echo.
echo Post-push verification:
echo   git log --oneline -3
echo   git rev-list --count origin/main..HEAD   ^(should be 0^)
echo.
pause
