/**
 * GitStore — workspace 数据演化的 git 历史层（isomorphic-git，纯 Node）
 *
 * 设计文档：doc/agent-data-state-machine.md §7
 *
 * 职责：
 *   1. 首次接触 workspace → 自动 `git init` 并提交 initial 占位
 *   2. 每次有意义的状态变更后调用 commit(message, meta) → 自动 stage + commit
 *   3. 同一作者签名（Author: agent <agent@kuroneko.local>），运维/LLM 自己的 commit
 *      可以用不同 author 区分
 *
 * 通过 UTLRA_AGENT_GIT=0 全局关闭（兜底开关，默认开启）。
 *
 * 注意：
 *   - 不调用系统 `git`，也不调用 `hutao`（避免 PowerShell PATH 问题）。
 *   - workspace 内 repo 不与远端发生关系；纯本地演化史。
 */

import fs from 'node:fs';
import path from 'node:path';
import git from 'isomorphic-git';

const DEFAULT_AUTHOR = { name: 'agent', email: 'agent@kuroneko.local' };
const GITIGNORE_DEFAULT = [
  '# autogenerated by GitStore — 数据本体进 git，派生物不进',
  '.run/',
  '*.log',
  '.tool-outputs/',
  'node_modules/',
  '*.tmp',
  '*.swp',
  '',
].join('\n');

export interface CommitMeta {
  mode?: string;
  milestone?: string;
  burstId?: string;
  kpiId?: string;
  ticks?: number;
  /** 强制使用此 author（LLM 自指写 git 时区分） */
  author?: { name: string; email: string };
}

export interface GitStore {
  readonly enabled: boolean;
  init(): Promise<void>;
  commit(message: string, meta?: CommitMeta): Promise<string | null>;
  /** 当前 HEAD 的 oid，没初始化时返回 null */
  head(): Promise<string | null>;
}

class NoopGitStore implements GitStore {
  readonly enabled = false;
  async init(): Promise<void> { /* noop */ }
  async commit(): Promise<string | null> { return null; }
  async head(): Promise<string | null> { return null; }
}

class IsomorphicGitStore implements GitStore {
  readonly enabled = true;
  private inited = false;
  constructor(private readonly workDir: string) {}

  async init(): Promise<void> {
    if (this.inited) return;
    const gitDir = path.join(this.workDir, '.git');
    if (!fs.existsSync(gitDir)) {
      fs.mkdirSync(this.workDir, { recursive: true });
      await git.init({ fs, dir: this.workDir, defaultBranch: 'main' });
      const gitignorePath = path.join(this.workDir, '.gitignore');
      if (!fs.existsSync(gitignorePath)) {
        fs.writeFileSync(gitignorePath, GITIGNORE_DEFAULT, 'utf8');
      }
      // 占位 commit，保证 HEAD 存在
      await git.add({ fs, dir: this.workDir, filepath: '.gitignore' });
      try {
        await git.commit({
          fs,
          dir: this.workDir,
          message: '[init] workspace created',
          author: DEFAULT_AUTHOR,
        });
      } catch {
        /* 第一次 add 失败也继续，后续 commit 会再尝试 */
      }
    }
    this.inited = true;
  }

  async commit(message: string, meta: CommitMeta = {}): Promise<string | null> {
    try {
      await this.init();
      // stage 全部已变更（不强制 add 未跟踪的二进制大文件——.gitignore 已挡掉派生物）
      await stageAllChanges(this.workDir);
      const status = await git.statusMatrix({ fs, dir: this.workDir });
      const dirty = status.some(([, head, work, stage]) => head !== work || head !== stage);
      if (!dirty) return null;
      const author = meta.author ?? DEFAULT_AUTHOR;
      const fullMessage = buildCommitMessage(message, meta);
      const oid = await git.commit({ fs, dir: this.workDir, message: fullMessage, author });
      return oid;
    } catch (e) {
      // git 写入失败不致命（agent 主流程仍然能跑）
      console.warn('[git-store] commit failed:', (e as Error).message);
      return null;
    }
  }

  async head(): Promise<string | null> {
    try {
      await this.init();
      const oid = await git.resolveRef({ fs, dir: this.workDir, ref: 'HEAD' });
      return oid;
    } catch {
      return null;
    }
  }
}

function buildCommitMessage(message: string, meta: CommitMeta): string {
  const lines: string[] = [message];
  const detailParts: string[] = [];
  if (meta.mode)       detailParts.push(`mode=${meta.mode}`);
  if (meta.milestone)  detailParts.push(`milestone=${meta.milestone}`);
  if (meta.burstId)    detailParts.push(`burst=${meta.burstId}`);
  if (meta.kpiId)      detailParts.push(`kpi=${meta.kpiId}`);
  if (typeof meta.ticks === 'number') detailParts.push(`ticks=${meta.ticks}`);
  if (detailParts.length > 0) {
    lines.push('');
    lines.push(detailParts.join(' '));
  }
  return lines.join('\n');
}

/**
 * stage 全部变更（增/改/删都包含），等价于 `git add -A`。
 * isomorphic-git 没直接的 add -A，需要自己遍历 statusMatrix。
 */
async function stageAllChanges(dir: string): Promise<void> {
  const matrix = await git.statusMatrix({ fs, dir });
  for (const row of matrix) {
    const [filepath, head, work, stage] = row;
    if (head === work && work === stage) continue;
    if (work === 0) {
      // 已删除
      await git.remove({ fs, dir, filepath }).catch(() => {});
    } else {
      await git.add({ fs, dir, filepath }).catch(() => {});
    }
  }
}

// ── 工厂 ──────────────────────────────────────────────────────────────────────

function isEnabled(): boolean {
  const v = process.env['UTLRA_AGENT_GIT'];
  if (v === undefined) return true;
  return v !== '0' && v.toLowerCase() !== 'false' && v.toLowerCase() !== 'off';
}

export function createGitStore(workDir: string): GitStore {
  if (!isEnabled()) return new NoopGitStore();
  return new IsomorphicGitStore(workDir);
}
